config/routes.rb
Rails.application.routes.draw do
  resources :documents do
    get :e_sign, on: :member
  end
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  has_attached_file :file
  validates_attachment :file, content_type: { content_type: ["application/pdf", "application/msword"] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy, :e_sign]

  def index
    @documents = Document.all
  end

  def show
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)

    if @document.save
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render "new"
    end
  end

  def update
    if @document.update(document_params)
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render "edit"
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path, notice: 'Document was successfully destroyed.'
  end

  def e_sign
    client = HelloSign::Client.new :api_key => '658d53b22fc04533f913ff2c2096373009ecfb1285447b958eab53b45983ee5c'
    client.create_embedded_signature_request({
      test_mode: 1,
      client_id: '8e743f6d6245c07a1b907741b543fb14',
      title: 'NDA with Acme Co.',
      subject: 'The NDA we talked about',
      message: 'Please sign this NDA and then we can discuss more. Let me know if you have any questions.',
      signers: [
        {
          email_address: 'palash.bera@capitalnumbers.com',
          name: 'Palash Bera'
        }
      ],
      attachments: [{
        name: 'NDA',
        required: true
        }
      ],
      files: ['NDA.pdf']
    })
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:name, :file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document, local: true) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.file %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>File:</strong>
  <%= link_to "Download", @document.file.url(:original) %>
</p>

<p>
  <strong>E-sign</strong>
  <%= link_to "eSign", e_sign_document_path(@document) %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<%= link_to "Documents", documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloSign</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>